GET http://localhost:8383

### Athentication Endpoints
POST http://localhost:8383/auth/register
Content-Type: application/json

{
    "username": "mithun",
    "password": "123"
}
###
POST http://localhost:8383/auth/login
Content-Type: application/json

{
    "username": "mithun",
    "password": "123"
}

### TODOs Endpoints
GET http://localhost:8383/todos/
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzY1MDE1OTI2LCJleHAiOjE3NjUxMDIzMjZ9.dFXGhUS5fIWKOXVEHbmO1ojV4CaQqO3lnPGludiGTpU

###
POST http://localhost:8383/todos/
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzY1MDE1OTI2LCJleHAiOjE3NjUxMDIzMjZ9.dFXGhUS5fIWKOXVEHbmO1ojV4CaQqO3lnPGludiGTpU
Content-Type: application/json

{
    "task" : "Complete the projects"
}

###
PUT http://localhost:8383/todos/2
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzY1MDE1NTYyLCJleHAiOjE3NjUxMDE5NjJ9.CuoTJpvWyEAf7IUe_9ufJ5MFRdEB_FZWFJJJev1Cdw8
Content-Type: application/json

{
    "completed": 1
}

###
DELETE http://localhost:8383/todos/2
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzY1MDE1NTYyLCJleHAiOjE3NjUxMDE5NjJ9.CuoTJpvWyEAf7IUe_9ufJ5MFRdEB_FZWFJJJev1Cdw8
